services:
  server:
    build:
      context: .
    environment:
      SERVER_ADDR: http://server:8080
    ports:
      - "8080:8080"
    command: "/usr/local/bin/server"
    #command: ["sh", "-c", "tail -f /dev/null"]
  client:
    build:
      context: .
    environment:
      SERVER_ADDR: http://server:8080
    stdin_open: true
    tty: true
    command: ["sh", "-c", "tail -f /dev/null"]