services:
  build:
    build:
      dockerfile: Dockerfile.build
      target: build-zkp-auth
    command: cargo build --release
    volumes:
        - .:/usr/src/myapp
        - build:/usr/src/zkp-auth/target
  server:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - build
    volumes:
        - build:/usr/src/zkp-auth/target
    command: "/usr/src/zkp-auth/target/release/server"
  client:
    build:
      context: .
    environment:
      SERVER_ADDR: server:8080
    depends_on:
      - build
    volumes:
      - build:/usr/src/zkp-auth/target
    command: ["sh", "-c", "tail -f /dev/null"]

volumes:
  build:
    driver: local