FROM rust:1.67 as build

RUN apt update
RUN apt install protobuf-compiler -y

FROM build as build-zkp-auth
WORKDIR /usr/src/zkp-auth
COPY . .

CMD ["cargo", "build", "--release", "--bin", "client", "--bin", "server"]